services:
  db:
    image: postgres:16-alpine
    container_name: db
    env_file:
      - .env
    expose:
      - "5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./internal/db/schema.sql:/docker-entrypoint-initdb.d/001_schema.sql:ro

  rustfs:
    image: rustfs/rustfs:latest
    container_name: rustfs
    command: /data
    env_file:
      - .env
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - rustfs_data:/data

  app:
    container_name: app
    build: .
    ports:
      - "8080:8080"
    env_file:
      - .env
    depends_on:
      - db
      - rustfs
    restart: always

volumes:
  db_data:
  rustfs_data:
